name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m pip install numpy scipy
        sudo apt update
        sudo apt install -y libomp-dev
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install module
      run: |
        python -m build
        python -m pip install dist/*.whl
    - name: Test
      run: |
        python tests/reg_creation_tests.py 1 14
        python tests/one_gate_tests.py 1 14 1
        python tests/one_gate_tests.py 1 14 4
        python tests/measure_tests.py 1 10 1000 1
        python tests/measure_tests.py 1 10 1000 4
        python tests/multiple_gate_tests.py 2 10 1
        python tests/multiple_gate_tests.py 2 10 4
        python tests/join_regs_tests.py 14 1
        python tests/join_regs_tests.py 14 4
        python tests/canonical_form_tests.py 1 14
        python tests/probability_tests.py 1 14 1
        python tests/probability_tests.py 1 14 4
    - uses: actions/upload-artifact@v2
      with:
        name: doki-artifact
        path: dist/ # or path/to/artifact
        if-no-files-found: error
