name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        #os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install MSVC compiler on Windows
        if: startsWith(matrix.os, 'Windows')
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OpenMP
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
               sudo apt install -y libomp-dev
             elif [ "$RUNNER_OS" == "Windows" ]; then
               echo "OpenMP already installed on Windows"
             elif [ "$RUNNER_OS" == "macOS" ]; then
               #brew install llvm
               brew install libomp
               ls -al /opt/homebrew/Cellar/libomp
             else
               echo "$RUNNER_OS not supported"
               exit 1
             fi
        shell: bash

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels on macOS
        if: startsWith(matrix.os, 'macOS')
        run: |
             ls -al /opt/homebrew/Cellar/libomp
             export CIBW_ENVIRONMENT_MACOS="LDFLAGS=\"-L/opt/homebrew/Cellar/libomp/18.1.8\" CPPFLAGS=\"-I/opt/homebrew/Cellar/libomp/18.1.8/include\""
             python -m cibuildwheel --output-dir wheelhouse

      - name: Build wheels not on macOS
        if: "!startsWith(matrix.os, 'macOS')"
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
