name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install MSVC compiler on Windows
        if: startsWith(matrix.os, 'Windows')
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OpenMP
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
               sudo apt install -y libomp-dev
             elif [ "$RUNNER_OS" == "Windows" ]; then
               echo "OpenMP already installed on Windows"
             elif [ "$RUNNER_OS" == "macOS" ]; then
               brew install libomp
             else
               echo "$RUNNER_OS not supported"
               exit 1
             fi
        shell: bash

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.17.0

      - name: Build wheels
        run: |
             if [ "$RUNNER_OS" == "Windows" ]; then
               echo $PATH
               PATH=$(echo "$PATH" | sed -e 's/:\/mingw64\/bin$//')
               PATH=$(echo "$PATH" | sed -e 's/:\/usr\/bin$//')
               echo $PATH
             elif [ "$RUNNER_OS" == "macOS" ]; then
               export LDFLAGS="-L/usr/local/opt/libomp/lib"
               export CPPFLAGS="-I/usr/local/opt/libomp/include"
             fi
             python -m cibuildwheel --output-dir wheelhouse
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
